// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLHjkH0nT8XOMmIiuGpgfuMOSt_f-oaE',
    appId: '1:179957743928:android:2e5da47c63530034e0c1cd',
    messagingSenderId: '179957743928',
    projectId: 'realtime-database-les',
    databaseURL: 'https://realtime-database-les-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-database-les.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsGKFcuSl64Fu-AmiDhFJtQPzSvvTCqE',
    appId: '1:179957743928:ios:8851cae0344d328be0c1cd',
    messagingSenderId: '179957743928',
    projectId: 'realtime-database-les',
    databaseURL: 'https://realtime-database-les-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-database-les.appspot.com',
    iosClientId: '179957743928-2ji0p7fvjmh17u65j27v17qjaut21fpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeDatabase',
  );
}
